name: artifact
on: 
    push:
        branches:
            - main

permissions: 
        contents: write
        pull-requests: write

jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate and upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact.zip
          path: |
            src/images/background_mainpage.jpg
            index.html
            style.css
  deploy:
    runs-on: ubuntu-lastest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: my-artifact.zip

      - name: Display structure of downloaded files
        run: ls -R
