name: artifact
on: 
    push:
        branches:
            - main

permissions: 
        contents: write
        pull-requests: write

jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:
      - name: generating artifact
        uses: actions/upload-artifact@v4
        with:
            name: my-artifact.zip
            path: |
                /src/
                index.html
                style.css
