name: artifact
on: 
    push:
        branches:
            - main

permissions: 
        contents: write
        pull-requests: write

jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:
      - name: generating artifact
        uses: actions/upload-artifact@v4
        with:
            name: my-artifact.zip
            path: |
                ${{ github.workspace }}/src/images/background_mainpage.jpg
                index.html
                style.css
