---
    name: Lint
    
    on: # yamllint disable-line rule:truthy
      push: null
      pull_request: null
    
    permissions: 
        contents: write
        pull-requests: write
    
    jobs:
      build:
        name: Lint
        runs-on: ubuntu-latest
    
        permissions:
          contents: read
          packages: read
          # To report GitHub Actions status checks
          statuses: write
    
        steps:
          - name: Checkout code
            uses: actions/checkout@v4
            with:
              # super-linter needs the full git history to get the
              # list of files that changed across commits
              fetch-depth: 0
    
          - name: Super-linter
            uses: super-linter/super-linter@v7.3.0 # x-release-please-version
            env:
              # To report GitHub Actions status checks
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              VALIDATE_CSS_PRETTIER: false
              VALIDATE_HTML_PRETTIER: false
              VALIDATE_MARKDOWN_PRETTIER: false
              VALIDATE_YAML_PRETTIER: false

      discord:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v4   
        - name: Discord Commits
          uses: Sniddl/discord-commits@v1.6
          with:
            webhook: ${{ secrets.DISCORD_WEBHOOK }}
            template: "avatar-with-link"
            include-extras: true
