---
    name: Lint
    
    on: # yamllint disable-line rule:truthy
      push: null
      pull_request: null
    
    permissions: 
        contents: write
        pull-requests: write
    
    jobs:
      build:
        name: Lint
        runs-on: ubuntu-latest
    
        permissions:
          contents: read
          packages: read
          # To report GitHub Actions status checks
          statuses: write
    
        steps:
          - name: Checkout code
            uses: actions/checkout@v4
            with:
              # super-linter needs the full git history to get the
              # list of files that changed across commits
              fetch-depth: 0
    
          - name: Super-linter
            uses: super-linter/super-linter@v7.3.0 # x-release-please-version
            env:
              # To report GitHub Actions status checks
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              VALIDATE_CSS_PRETTIER: false
              VALIDATE_HTML_PRETTIER: false
              VALIDATE_MARKDOWN_PRETTIER: false
              VALIDATE_YAML_PRETTIER: false

      discord:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v4   
        - name: Discord Commits
          uses: Sniddl/discord-commits@v1.6
          with:
            webhook: ${{ secrets.DISCORD_WEBHOOK }}
            template: "avatar-with-link"
            include-extras: true
      
      testes:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.x'
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        - name: Test with pytest
          run: |
              pip install pytest pytest-cov
              pytest test/test.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html

